### ISSUE TITLE
Do we need to track the address/port info in the controller?

### ISSUE THREAD

**Issue by sterlingbaldwin** [sterlingbaldwin/scalable_project_3#16]
See: https://github.com/sterlingbaldwin/scalable_project_3/blob/main/MainController.py#L133

Do we need this, or is it superfluous? The ship/stations need to know the server address/port in order to communicate, but the ships arent listening for connections, the only make connections out to the server, so Im not sure that these are meaningful. Am I missing something?

@Zhouhao-Rui @Angkirat

**Comment by Zhouhao-Rui** [comment]
Yes, I think we can remove the port and address directly. Sorry for that!

**Comment by Angkirat** [comment]
I thought there was a peer to peer communication that needs to be performed so that is why

**Comment by sterlingbaldwin** [comment]
No worries! Thought I was missing something.
